# Compose file for developing
version: "3"

services:
  db:
    build: ./psql/
    container_name: checks_review_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$PSQL_DB_NAME
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_PASSWORD=$PSQL_PASSWORD
    networks:
      - checks_review_net


  redis:
    image: redis:latest
    container_name: checks_review_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - checks_review_net
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  
  adminer:
    image: adminer:latest
    container_name: checks_review_adminer
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - checks_review_net
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}


  backend:
    build: ./backend/
    container_name: checks_review_backend
    volumes:
      - db:/var/lib/postgresql/data
      - ./backend/:/backend/
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - checks_review_net
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}


networks:
  checks_review_net:

volumes:
  db:
