"""Product, Position, Receipt

Revision ID: c13042a9908e
Revises: 58891f4fb0b9
Create Date: 2024-02-27 12:09:49.590375

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c13042a9908e"
down_revision = "58891f4fb0b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=40), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    op.create_table(
        "receipt",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.VARCHAR(), nullable=False),
        sa.Column("rest", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipt_id"), "receipt", ["id"], unique=False)
    op.create_table(
        "position",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("receipt_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipt.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_id"), "position", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_position_id"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_receipt_id"), table_name="receipt")
    op.drop_table("receipt")
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    # ### end Alembic commands ###
